### ISSUE TITLE
Please tag the 2019.2 release

### ISSUE THREAD

**Issue by rc-matthew-l-weber** [Xilinx/bootgen#1]
I'm adding a package to buildroot to support this tool and would like to reference a released tag.

**Comment by prashant-malladi** [comment]
There are few more changes in pipeline for 2019.2 release. We'll tag the release once they are pushed in.

**Comment by rc-matthew-l-weber** [comment]
I haven't opened a issue yet but it looks like the bison/flex stuff should be regenerated at build time.  The newer versions 3.4+ we have in embedded builds aren't compatible with the auto-generated code which has been checked in.
