### ISSUE TITLE
xip_mode ignores the offset=<addr> value

### ISSUE THREAD

**Issue by johandc** [Xilinx/bootgen#2]
When using XIP mode, the offset of the image always becomes 0x1700, no matter what the offset=<addr> is set to.

The error is in partition.cpp line 232
` 
     if(header->imageHeader->GetXipMode())
        {
`
This function returns false, even when xip_mode is set.

**Comment by RamyaDarapuneni** [comment]
Fixed with Commit ID : a10d8721a7da93526ccf9760d89cc487446cf5aa
