### ISSUE TITLE
bootgen blindly assumes all ELF32 headers are ARMv7/AArch32

### ISSUE THREAD

**Issue by KinseyMoore** [Xilinx/bootgen#7]
In ElfFormat::GetElfFormat() in elftools.cpp, it is blindly assumed that all ELF32 headers are associated with AArch32 code. The ILP32 data model of AArch64 also uses a ELF32 header which causes bl31 from ARM Trusted Firmware to incorrectly jump to the contained code in AArch32 mode which, for obvious reasons, does not end well.

**Comment by RamyaDarapuneni** [comment]
Merged with :
https://github.com/Xilinx/bootgen/commit/34c4313a09dd75cf6ff5b188136e1a077c5b0aa2#diff-11e838d439b638407b6c50a4bcd5094799922aabb0078b08c4fbaf9624e4a54b
